# Generated by Django 4.1.2 on 2022-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='social_link_field',
        ),
        migrations.AddField(
            model_name='artist',
            name='social_link',
            field=models.CharField(default=('blank',), max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='stage_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
