# Generated by Django 4.1.2 on 2022-10-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_social_link_field_artist_social_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='approved_album',
            field=models.IntegerField(default=0),
        ),
    ]
