# Generated by Django 4.1.2 on 2022-10-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artist_approved_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='approved_album',
        ),
    ]
