# Generated by Django 4.1.2 on 2022-10-12 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_artist_approved_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='approved_album',
            new_name='approved_albums',
        ),
    ]
