# Generated by Django 4.1.2 on 2022-10-06 21:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_artist_social_link_field_artist_social_link_and_more'),
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='creation_day',
            field=models.DateField(default=datetime.datetime(2022, 10, 6, 21, 26, 48, 220920, tzinfo=datetime.timezone.utc), verbose_name=datetime.datetime(2022, 10, 6, 21, 25, 59, 964003, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='New Album', max_length=60),
        ),
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 6, 21, 25, 59, 964003, tzinfo=datetime.timezone.utc)),
        ),
    ]
