# Generated by Django 4.1.2 on 2022-10-06 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_artist_id_album_creation_day_album_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_day',
            field=models.DateField(default=datetime.datetime(2022, 10, 6, 23, 51, 41, 990079, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 6, 23, 51, 41, 990079, tzinfo=datetime.timezone.utc)),
        ),
    ]
