# Generated by Django 4.1.2 on 2022-10-12 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_alter_album_artist_id_alter_album_creation_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_day',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 11, 52, 15, 186820, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 11, 52, 15, 186820, tzinfo=datetime.timezone.utc)),
        ),
    ]
