# Generated by Django 4.1.2 on 2022-10-12 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_alter_album_creation_day_alter_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='approved_albums',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_day',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 11, 59, 45, 622266, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 11, 59, 45, 622266, tzinfo=datetime.timezone.utc)),
        ),
    ]
