# Generated by Django 4.1.2 on 2022-10-12 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0011_album_approved_albums_alter_album_creation_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='creation_day',
        ),
        migrations.AddField(
            model_name='album',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 12, 18, 24, 891777, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 12, 18, 24, 891777, tzinfo=datetime.timezone.utc)),
        ),
    ]
