# Generated by Django 4.1.2 on 2022-10-12 21:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0013_alter_album_approved_albums_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 46, 21, 40761, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 46, 21, 40761, tzinfo=datetime.timezone.utc)),
        ),
    ]
