# Generated by Django 4.1.2 on 2022-10-12 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0014_alter_album_creation_date_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 48, 55, 462022, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 48, 55, 462022, tzinfo=datetime.timezone.utc)),
        ),
    ]
