# Generated by Django 4.1.2 on 2022-10-12 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0015_alter_album_creation_date_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 50, 7, 864399, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 50, 7, 864399, tzinfo=datetime.timezone.utc)),
        ),
    ]
