# Generated by Django 4.1.2 on 2022-10-12 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0016_alter_album_creation_date_alter_album_release_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='approved_albums',
            new_name='is_approved',
        ),
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 54, 49, 142479, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 12, 21, 54, 49, 142479, tzinfo=datetime.timezone.utc)),
        ),
    ]
