# Generated by Django 4.1.2 on 2022-10-15 13:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0017_rename_approved_albums_album_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
